export const LANDING_DEFAULTS: Record<string, string> = {
  promo_text: "LIVRAISON OFFERTE DÈS 15 000 DA",
  promo_visible: "1",
  promo_text_color: "",
  promo_bg_color: "",
  promo_font_size: "",
  promo_font_weight: "",
  promo_border_radius: "",
  promo_padding_y: "",
  promo_padding_x: "",
  hero_eyebrow: "DROP EN COURS — 69 WILAYAS",
  hero_title: "LIKE IT. WANT IT. COP IT.",
  hero_subtitle: "SNEAKERS & STREETWEAR 100% ORIGINAUX",
  hero_cta1: "Voir le Drop",
  hero_cta2: "Promos",
  hero_visual_img: "",
  hero_visual_sku: "SKU // CP-0192",
  hero_visual_title: "New Arrival",
  hero_visual_stat: "28K+",
  hero_visual_stat_label: "COPPERS",
  cat_title: "Shop par catégorie",
  cat_cta: "Le Shop",
  new_title: "Dernières Sneakers",
  latestSneakersEnabled: "1",
  latestSneakersLimit: "10",
  latestSneakersSortOrder: "position",
  why_title: "Pourquoi COP chez nous",
  why_badge: "AUTHENTICITÉ VÉRIFIÉE",
  btn_voir_plus: "VOIR PLUS",
  btn_tout_voir: "TOUT VOIR",
  faq_title: "Questions fréquentes",
  new_arrival_title: "Nouveautés",
  new_arrival_subtitle: "Fraîchement arrivés cette semaine.",
  promo_title: "Promotions",
  promo_subtitle: "Articles en promotion",
  foot_phone: "0562 82 98 05",
  foot_rights: "Tous droits réservés.",
  foot_conf: "Confidentialité",
  foot_cond: "Conditions",
  foot_admin: "Admin",
  banner_chaussures_img: "",
  banner_promo_img: "",
};
